# Default values for cloudflare argo-tunnel ingress.
controller:
  name: controller
  image:
    repository: gcr.io/cloudflare-registry/argo-tunnel
    tag: "0.6.2"
    pullPolicy: Always
  ingressClass: argo-tunnel
  logLevel: 3
  replicaCount: 1
  resyncPeriod: 5m
  workers: 2
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
# Enable load balancing
# requires load balancing enabled on the cloudflare account.
loadBalancing:
  enabled: false

# Enable rbac
rbac:
  create: true
  name:

serviceAccount:
  create: true
  name:

# Enable secret mapping file
secretMapping:
  create: false
  content:
    {}